package com.star.cook.dao;

import com.star.cook.entity.Achievemenkindtinfo;
import java.util.List;

public interface AchievemenkindtinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    int insert(Achievemenkindtinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    Achievemenkindtinfo selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    List<Achievemenkindtinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Achievemenkindtinfo record);
}