package com.star.cook.dao;

import com.star.cook.entity.Commentinfo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("commentid") Integer commentid, @Param("userid") Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    int insert(Commentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    Commentinfo selectByPrimaryKey(@Param("commentid") Integer commentid, @Param("userid") Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    List<Commentinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Commentinfo record);
}