package com.star.cook.dao;

import com.star.cook.entity.Friendrange;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("userid") Integer userid, @Param("friendid") Integer friendid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    int insert(Friendrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    Friendrange selectByPrimaryKey(@Param("userid") Integer userid, @Param("friendid") Integer friendid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    List<Friendrange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Friendrange record);
}