package com.star.cook.dao;

import com.star.cook.entity.Reward;
import java.util.List;

public interface RewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    int insert(Reward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    List<Reward> selectAll();
}