package com.star.cook.entity;

import java.io.Serializable;

public class Articleinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.articleId
     *
     * @mbggenerated
     */
    private Integer articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.urls
     *
     * @mbggenerated
     */
    private String urls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.praiseNum
     *
     * @mbggenerated
     */
    private Integer praisenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.readNum
     *
     * @mbggenerated
     */
    private Integer readnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.commentNum
     *
     * @mbggenerated
     */
    private Integer commentnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.avgscore
     *
     * @mbggenerated
     */
    private Integer avgscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.creatStamp
     *
     * @mbggenerated
     */
    private Long creatstamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.isTop
     *
     * @mbggenerated
     */
    private Integer istop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table articleinfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.articleId
     *
     * @return the value of articleinfo.articleId
     *
     * @mbggenerated
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.articleId
     *
     * @param articleid the value for articleinfo.articleId
     *
     * @mbggenerated
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.title
     *
     * @return the value of articleinfo.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.title
     *
     * @param title the value for articleinfo.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.urls
     *
     * @return the value of articleinfo.urls
     *
     * @mbggenerated
     */
    public String getUrls() {
        return urls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.urls
     *
     * @param urls the value for articleinfo.urls
     *
     * @mbggenerated
     */
    public void setUrls(String urls) {
        this.urls = urls == null ? null : urls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.praiseNum
     *
     * @return the value of articleinfo.praiseNum
     *
     * @mbggenerated
     */
    public Integer getPraisenum() {
        return praisenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.praiseNum
     *
     * @param praisenum the value for articleinfo.praiseNum
     *
     * @mbggenerated
     */
    public void setPraisenum(Integer praisenum) {
        this.praisenum = praisenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.readNum
     *
     * @return the value of articleinfo.readNum
     *
     * @mbggenerated
     */
    public Integer getReadnum() {
        return readnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.readNum
     *
     * @param readnum the value for articleinfo.readNum
     *
     * @mbggenerated
     */
    public void setReadnum(Integer readnum) {
        this.readnum = readnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.commentNum
     *
     * @return the value of articleinfo.commentNum
     *
     * @mbggenerated
     */
    public Integer getCommentnum() {
        return commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.commentNum
     *
     * @param commentnum the value for articleinfo.commentNum
     *
     * @mbggenerated
     */
    public void setCommentnum(Integer commentnum) {
        this.commentnum = commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.avgscore
     *
     * @return the value of articleinfo.avgscore
     *
     * @mbggenerated
     */
    public Integer getAvgscore() {
        return avgscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.avgscore
     *
     * @param avgscore the value for articleinfo.avgscore
     *
     * @mbggenerated
     */
    public void setAvgscore(Integer avgscore) {
        this.avgscore = avgscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.creatStamp
     *
     * @return the value of articleinfo.creatStamp
     *
     * @mbggenerated
     */
    public Long getCreatstamp() {
        return creatstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.creatStamp
     *
     * @param creatstamp the value for articleinfo.creatStamp
     *
     * @mbggenerated
     */
    public void setCreatstamp(Long creatstamp) {
        this.creatstamp = creatstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.isTop
     *
     * @return the value of articleinfo.isTop
     *
     * @mbggenerated
     */
    public Integer getIstop() {
        return istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.isTop
     *
     * @param istop the value for articleinfo.isTop
     *
     * @mbggenerated
     */
    public void setIstop(Integer istop) {
        this.istop = istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleinfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleid=").append(articleid);
        sb.append(", title=").append(title);
        sb.append(", urls=").append(urls);
        sb.append(", praisenum=").append(praisenum);
        sb.append(", readnum=").append(readnum);
        sb.append(", commentnum=").append(commentnum);
        sb.append(", avgscore=").append(avgscore);
        sb.append(", creatstamp=").append(creatstamp);
        sb.append(", istop=").append(istop);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}